
var randomstuff = [
    '34543535th update',
    'imagine having to update your page',
    'big update???',
    'i have to rewrite everything...',
    'please stop',
    'no',
    'arriba españa',
    'version 3.53452345235',
    'i agree',
    'i am probably doing a mess rn',
    'maybe im fucking up the code',
    'i MIGHT be doing something wrong',
    'SanicBTW was here',
    'xhyabunny is thicc',
    'help',
    'bonndubz on all socials (except on twitter because twitter sucks)',
    '@TwtBonn on twitter',
    'yeah i took this idea from sanic',
    'el pollo',
    '?',
    'visual studio sucks',
    'get outta here',
    'h',
    'im probably updating something really stupid',
    'Lunes',
    'coding.',
    'uwu',
    'pain',
    'please end with me',
    'sanic why',
    'i wanna die',
    'AYO THE PIZZA HERE',
    'abbadon is a cool manager',
    '404',
    'you heard it, get out',
    'joe',
    'joe mama',
    'riddim music',
    'polyriddim',
    'fix C# variables it sucks so bad thank you',
    'TOO MUCH ON THE LIST',
    'please have mercy',
    'oh god.',
    'not again-',
    'bruh',
    'fr?',
    ':skull:',
    'insert cringe ahh text',
    'please end with this',
    '*hammer and screwdriver sounds*',
    'build number 3832963257 intensifies',
    'im a slave of my own goals, please take me outside',
    'i need to see sunlight',
    'some day i will actually go outside, i swear',
    'yes.',
    'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA',
    'webpage forked from sanic lmao sorry g',
    'fml',
    'i love js',
    'i hate js',
    'i love cs', 
    'i hate cs',
    'i love html',
    'i hate html',
    'i love u',
    'i hate u',
    'jk, or was i..'
    'm',
    'a',
    'b',
    'KFDJGIKDHPRIOGUAEHJPBIDFUHBIERAPDFOSBNOIFDKHBNAFGJMBVPFHBNFDIKHJDA',
    '+`´`+eñ+t`4ñ3+`´´ñ+34`ñ+43`ñ+`ñ+´ñ`ñ`-+`hgñdfg+`jfd+`ñFG`js',
];

document.getElementById('random').innerText = randomstuff[Math.floor(Math.random() * randomstuff.length)];

document.body.addEventListener('keydown', (key) => {
    if(key.key == "r")
    {
        document.getElementById('random').innerText = randomstuff[Math.floor(Math.random() * randomstuff.length)];
    }
});
